In [1]:
import pandas as pd

In [2]:
pd.read_csv('/Users/lincoln.harris/Desktop/fusions_by_patient.csv')

       patientID  ALK--EML4  ALK_any  EML4_any  NTRK_any  RET_any  ROS1_any
0          TH185          0        3         5         0        0         0
1          TH266          2        1         3         1        2         1
2          H1975          0        0         0         0        0         0
3          TH171          3        4         2         0        2         0
4          TH155          0        0         0         0        0         0
5          TH188          0        0         0         0        0         0
6          TH082          0        0         0         0        0         0
7          TH103          4        3         3         0        0         1
8          TH214          0        0         0         0        0         0
9          TH153          0        0         0         0        0         0
10         TH226          0        2         1         2        1         7
11         TH205          0        2         1         1        1         5
12         TH116          0        0         0         0        0         0
13         TH144          0        0         0         0        0         0
14         TH210          0        0         0         0        0         0
15         TH107          0        0         0         0        0         0
16         TH100          0        0         0         0        0         0
17         TH187          0        0         0         0        0         0
18         TH124          0        0         0         0        0         0
19         TH067          0        1         1         0        0         1
20         TH166          0        0         0         0        0         0
21        TH143B          0        0         0         0        0         0
22         TH178          0        0         0         0        0         0
23         TH158          0        0         0         0        0         0
24         TH257          0        0         0         0        0         0
25         TH217          0        0         0         0        0         0
26         TH041          0        0         0         0        0         0
27         TH225          0        0         0         0        0         0
28         TH174          0        0         0         0        0         0
29         TH146          0        0         0         0        0         3
30          TPH1          0        0         0         0        0         0
31         TH223          0        0         1         0        0         0
32         TH249          0        0         0         0        0         0
33         TH238          0        0         1         1        1         0
34         TH236          0        0         0         0        1         0
35         TH172          0        0         0         0        0         0
36     TH134_PDX          0        0         0         0        0         0
37         TH150          0        0         0         0        0         0
38         TH199          0        0         1         0        0         0
39         TH208          0        0         0         0        0         0
40         TH227          0        0         0         0        0         0
41  TH238_Normal          0        1         0         1        0         0
42         TH179          0        3         3         3        1         3
43  TH179_Normal          0        0         0         0        0         0
44         TH218          0        0         2         0        0         0
45         TH248          0        2         1         0        1         1
46         TH156          0        0         0         0        0         0
47         TH222          0        1         0         0        0         0
48         TH231          0        2         1         0        0         5
49         TH169          0        1         0         0        0         0
50         TH157          0        0         0         0        0         0
51         TH220          3        1         1         0        1         0
52         TH183          0        0         0         0        0         0