In [ ]:
#///////////////////////////////////////////////////////////
# script: addCoverageToValidationTable
# author: Lincoln
# date: 3.7.19
#
# This notebook adds ROI specific coverage, on a per-cell basis, 
# and then maps everything to the by-patient df. 
# Coverage comes from: 
#          checkCoverage_parallel.py
#///////////////////////////////////////////////////////////

In [2]:
import pandas as pd

In [23]:
validationTable_patients = pd.read_csv('/Users/lincoln.harris/Desktop/validationTable_patients.csv')
validationTable_patients

,patient,driver_gene,driver_mutation,mutations_found,numCells,numTumorCells,numTumorCells_w_coverage_to_ROI,numTumorCells_clinMut_found
0,TH248,EGFR,del19,"EGFR Q787Q,EGFR Q787Q,EGFR T903T,EGFR T903T,EG...",NaN,384,NaN,20
1,TH205,EGFR,L858R,"['ROS1 fusion', 'NTRK fusion', 'EGFR L858R', '...",NaN,9,NaN,0
2,TH217,EGFR,del19,[],NaN,4,NaN,0
3,TH185,EGFR,L858R,"['EGFR R521K', 'EGFR Q787Q', 'EGFR V536M', 'KR...",NaN,952,NaN,145
4,TH218,EGFR,L858R,"['EGFR P589L', 'BRAF G643G', 'EGFR T629T', 'EG...",NaN,11,NaN,0
5,TH172,BRAF,V600E,"['EGFR R521K', 'EGFR Q787Q', 'EGFR T629T']",NaN,0,NaN,0
6,TH226,EGFR,del19,"['ROS1 fusion', 'NTRK fusion', 'EGFR R1100S', ...",NaN,205,NaN,10
7,TH174,WT,NaN,[],NaN,0,NaN,0
8,TH231,ALK,fusion,"['ROS1 fusion', 'EGFR R521K', 'EML4 fusion', '...",NaN,353,NaN,1
9,TH179_Normal,ALK,fusion,"['EGFR T903T', 'BRAF G643G', 'EGFR Q787Q']",NaN,11,NaN,0
10,TH171,ALK,fusion,"['ALK-EML4 fusion', 'BRAF G469R', 'EGFR V1142V...",NaN,720,NaN,3
11,TH227,ALK,intron 19 rearrangement,"['EGFR T629T', 'EGFR R521K', 'EGFR Q787Q', 'EG...",NaN,17,NaN,0
12,TH222,ROS1,fusion,"['EGFR L1034I', 'EGFR R1100S', 'BRAF G643G', '...",NaN,7,NaN,0
13,TH220,ALK,fusion,"['ALK-EML4 fusion', 'EGFR T629T', 'BRAF G643G'...",NaN,107,NaN,3
14,TH158,EGFR,del19,"['KRAS A11A', 'BRAF R682W', 'KRAS G12C']",NaN,3,NaN,0
15,TH223,EGFR,del19,"['EGFR T903T', 'BRAF G643G']",NaN,7,NaN,0
16,TH156,ALK,fusion,[],NaN,0,NaN,0
17,TH183,EGFR,del19,[],NaN,0,NaN,0
18,TH155,EGFR,del19,[],NaN,0,NaN,0
19,TH236,EGFR,del19,"['EGFR K754E', 'EGFR R1100S', 'EGFR P1019L', '...",NaN,101,NaN,18
20,TH146,ROS1,ROS1-CD74,['ROS1 fusion'],NaN,0,NaN,0
21,TH179,BRAF,V600E,"['BRAF G466E', 'EGFR Q787Q', 'KRAS C118S', 'KR...",NaN,137,NaN,0
22,TH157,ALK,fusion,[],NaN,0,NaN,0
23,TH169,EGFR,del19,"['EGFR T629T', 'EGFR R521K', 'KRAS A11A', 'ALK...",NaN,178,NaN,23
24,TH225,KRAS,G12C,"['EGFR T629T', 'EGFR R521K', 'EGFR Q787Q', 'EG...",NaN,20,NaN,0
25,TH103,ALK,fusion,"['ALK-EML4 fusion', 'ROS1 fusion', 'EGFR T629T...",NaN,65,NaN,4
26,TH238,BRAF,V600E,"['EGFR P589L', 'EGFR T629T', 'KRAS G13V', 'EGF...",NaN,260,NaN,0
27,TH067,EGFR,del19,"['ROS1 fusion', 'BRAF G643G', 'EML4 fusion', '...",NaN,97,NaN,0
28,TH199,KRAS,G12C,[],NaN,0,NaN,0
29,TH266,ALK,fusion,"['ALK-EML4 fusion', 'ROS1 fusion', 'KRAS K88K'...",NaN,1,NaN,0
30,TH150,WT,NaN,[],NaN,0,NaN,0
31,TH210,ALK,fusion,"['EGFR T903T', 'BRAF G643G']",NaN,15,NaN,0
32,TH208,EGFR,L861Q,"['EGFR T629T', 'EGFR R521K', 'EGFR L861Q', 'EG...",NaN,1,NaN,1
33,TH107,EGFR,del19,['KRAS G12C'],NaN,0,NaN,0
34,TH238_Normal,BRAF,V600E,"['NTRK fusion', 'EGFR T629T', 'EGFR R521K', 'E...",NaN,4,NaN,0

In [3]:
validationTable_cells = pd.read_csv('/Users/lincoln.harris/Desktop/validationTable_cells.csv')
validationTable_cells

,cell,patient,clinical_driver_gene,clinical_mutation,mutations_found,coverage_to_ROI,clinical_mutation_found_bool,tumorCell_bool
0,P13_1001000339,TH169,EGFR,del19,NaN,NaN,0,1
1,C1_B002572,TH266,ALK,fusion,NaN,NaN,0,0
2,J2_B002573,TH266,ALK,fusion,NaN,NaN,0,0
3,P22_B003116,TH231,ALK,fusion,NaN,NaN,0,1
4,O22_B003191,TH226,EGFR,del19,NaN,NaN,0,0
5,J12_B003529,TH171,ALK,fusion,EGFR T903T,NaN,0,1
6,D14_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR T903T, EGFR T629T, EGFR Q787Q",NaN,0,1
7,F14_B003105,TH222,ROS1,fusion,NaN,NaN,0,0
8,P11_1001000340,TH169,EGFR,del19,NaN,NaN,0,1
9,E21_B003930,TH222,ROS1,fusion,EGFR T903T,NaN,0,0
10,N1_B002573,TH266,ALK,fusion,NaN,NaN,0,0
11,C20_B000422,TH238,BRAF,V600E,NaN,NaN,0,0
12,F14_B001007,NaN,NaN,NaN,"EGFR Q787Q, EGFR T629T",NaN,0,0
13,C21_B003920,TH236,EGFR,del19,NaN,NaN,0,0
14,E16_B003894,TH236,EGFR,del19,NaN,NaN,0,0
15,D20_B002097,TH238_Normal,BRAF,V600E,EGFR T903T,NaN,0,0
16,I4_B001558,TH179_Normal,ALK,fusion,NaN,NaN,0,1
17,J14_B002077,TH238,BRAF,V600E,NaN,NaN,0,0
18,L7_B003129,TH226,EGFR,del19,NaN,NaN,0,0
19,C7_B003113,TH218,EGFR,L858R,NaN,NaN,0,0
20,H18_B003116,TH231,ALK,fusion,NaN,NaN,0,0
21,I7_B002572,TH266,ALK,fusion,NaN,NaN,0,0
22,I1_B003187,TH226,EGFR,del19,NaN,NaN,0,0
23,N17_B003776,TH248,EGFR,del19,NaN,NaN,0,1
24,I8_B003659,TH067,EGFR,del19,NaN,NaN,0,0
25,P16_B003126,TH226,EGFR,del19,NaN,NaN,0,0
26,P9_B001007,NaN,NaN,NaN,NaN,NaN,0,0
27,B17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T",9.0,1,1
28,E20_B003646,TH226,EGFR,del19,NaN,NaN,0,0
29,N3_B000861,TH220,ALK,fusion,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...
9851,O15_B003995,TH236,EGFR,del19,NaN,NaN,0,0
9852,F12_B003894,TH236,EGFR,del19,NaN,NaN,0,0
9853,D12_B003771,TH236,EGFR,del19,NaN,NaN,0,0
9854,L21_B002077,TH238,BRAF,V600E,NaN,NaN,0,1
9855,B22_B003920,TH236,EGFR,del19,NaN,NaN,0,0
9856,E22_B003518,TH171,ALK,fusion,NaN,NaN,0,1
9857,N16_B000422,TH238,BRAF,V600E,NaN,NaN,0,0
9858,O12_B001010,NaN,NaN,NaN,NaN,NaN,0,0
9859,H4_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",4.0,1,1
9860,G17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",18.0,1,1
9861,D3_B001559,TH179,BRAF,V600E,KRAS A11A,NaN,0,0
9862,O8_B002572,TH266,ALK,fusion,KRAS K88K,NaN,0,0
9863,C14_B003894,TH236,EGFR,del19,NaN,NaN,0,1
9864,D22_B003775,TH248,EGFR,del19,NaN,NaN,0,0
9865,A15_B000420,TH238,BRAF,V600E,NaN,NaN,0,0
9866,O12_B003776,TH248,EGFR,del19,EGFR del19,NaN,1,1
9867,D14_B002097,TH238_Normal,BRAF,V600E,NaN,NaN,0,0
9868,H12_B002572,TH266,ALK,fusion,NaN,NaN,0,0
9869,A14_B002077,TH238,BRAF,V600E,NaN,NaN,0,0
9870,L9_1001000411,TH185,EGFR,L858R,NaN,NaN,0,1
9871,P9_B003067,TH205,EGFR,L858R,NaN,NaN,0,0
9872,J14_B003518,TH171,ALK,fusion,NaN,NaN,0,1
9873,B20_B000422,TH238,BRAF,V600E,NaN,NaN,0,0
9874,K4_B003187,TH226,EGFR,del19,NaN,NaN,0,0
9875,M17_B003894,TH236,EGFR,del19,NaN,NaN,0,1
9876,O9_B003527,TH171,ALK,fusion,NaN,NaN,0,1
9877,F15_B001008,NaN,NaN,NaN,NaN,NaN,0,0
9878,L20_B003777,TH248,EGFR,del19,NaN,NaN,0,1
9879,O9_1001000407,TH185,EGFR,L858R,EGFR Q787Q,NaN,0,1
9880,L3_B003129,TH226,EGFR,del19,NaN,NaN,0,0

In [4]:
egfr_L858R_cov = pd.read_csv('../coverage/out/egfr_L858R_coverageByCell.csv')
egfr_L858R_cov

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
0,A10_1001000407,0,0,0,0
1,A10_1001000408,0,0,0,0
2,A10_1001000412,0,0,0,0
3,A10_B000863,0,0,0,0
4,A10_B001007,0,0,0,0
5,A10_B001470,0,0,0,0
6,A10_B001474,0,0,0,0
7,A10_B001545,0,0,0,0
8,A10_B001548,0,0,0,0
9,A10_B001554,0,0,0,0
10,A10_B001558,0,0,0,0
11,A10_B002572,0,0,0,0
12,A10_B003070,0,0,0,0
13,A10_B003071,0,0,0,0
14,A10_B003115,0,0,0,0
15,A10_B003125,0,0,0,0
16,A10_B003518,0,0,0,0
17,A10_B003523,0,0,0,0
18,A10_B003527,0,0,0,0
19,A10_B003528,0,0,0,0
20,A10_B003529,0,0,0,0
21,A10_B003588,0,0,0,0
22,A11_1001000407,0,0,0,0
23,A11_1001000408,0,0,0,0
24,A11_1001000412,0,0,0,0
25,A11_B000860,0,0,0,0
26,A11_B000861,0,0,0,0
27,A11_B000862,0,0,0,0
28,A11_B001007,0,0,0,0
29,A11_B001470,0,0,0,0
...,...,...,...,...,...
9318,P8_B003518,0,0,0,0
9319,P8_B003527,0,0,0,0
9320,P8_B003648,0,0,0,0
9321,P8_B003658,0,0,0,0
9322,P8_B003995,0,0,0,0
9323,P9_1001000407,1,2,1,2
9324,P9_1001000408,1,2,1,6
9325,P9_B000281,0,0,0,0
9326,P9_B000419,0,0,0,0
9327,P9_B000861,0,0,0,0
9328,P9_B000862,0,0,0,0
9329,P9_B001007,0,0,0,0
9330,P9_B001470,0,0,0,0
9331,P9_B001475,0,0,0,0
9332,P9_B001543,0,0,0,0
9333,P9_B001545,0,0,0,0
9334,P9_B001548,0,0,0,0
9335,P9_B001554,0,0,0,0
9336,P9_B001558,0,0,0,0
9337,P9_B002573,0,0,0,0
9338,P9_B003067,0,0,0,0
9339,P9_B003071,0,0,0,0
9340,P9_B003187,0,0,0,0
9341,P9_B003518,0,0,0,0
9342,P9_B003527,0,0,0,0
9343,P9_B003528,0,0,0,0
9344,P9_B003577,0,0,0,0
9345,P9_B003656,0,0,0,0
9346,P9_B003658,0,0,0,0
9347,P9_B003995,0,0,0,0

In [5]:
# 200 cells here
indices = egfr_L858R_cov['depth_gvcf'] != 0
egfr_L858R_cov_nonZero = egfr_L858R_cov[indices]
egfr_L858R_cov_nonZero

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
66,A13_1001000407,1,12,1,23
67,A13_1001000408,0,0,1,2
121,A15_1001000408,0,0,1,3
153,A16_1001000407,1,6,1,15
155,A16_1001000412,1,16,1,29
185,A17_1001000407,0,0,1,5
212,A18_1001000408,0,0,1,2
285,A20_1001000408,1,6,1,14
384,A3_1001000412,0,0,1,3
542,B10_1001000412,1,3,1,7
588,B12_1001000412,1,2,1,6
607,B13_1001000407,0,0,1,6
609,B13_1001000412,1,3,1,4
660,B15_1001000407,0,0,1,26
730,B17_1001000407,1,6,1,9
732,B17_1001000412,0,0,1,3
783,B19_1001000407,1,17,1,28
824,B20_1001000407,0,0,1,2
875,B22_1001000407,1,8,1,19
876,B22_1001000408,0,0,1,2
974,B5_1001000412,1,3,1,6
1089,C10_1001000407,1,12,1,12
1114,C11_1001000407,1,10,1,19
1115,C11_1001000408,1,10,1,16
1160,C13_1001000408,1,3,1,3
1278,C17_1001000408,0,0,1,3
1310,C18_1001000407,1,3,1,3
1453,C22_1001000407,1,4,1,6
1454,C22_1001000408,1,2,1,2
1487,C2_1001000412,0,0,1,5
...,...,...,...,...,...
7684,N12_1001000407,1,3,1,4
7770,N15_1001000412,0,0,1,5
7838,N17_1001000408,1,3,1,3
7897,N19_1001000407,1,9,1,12
7944,N20_1001000407,1,2,1,5
7945,N20_1001000408,1,3,1,9
8043,N3_1001000407,0,0,1,4
8110,N6_1001000407,1,2,1,6
8207,O10_1001000407,1,3,1,3
8230,O11_1001000412,1,2,1,6
8251,O12_1001000407,0,0,1,3
8301,O14_1001000408,1,3,1,8
8370,O16_1001000412,1,6,1,9
8404,O17_1001000412,1,7,1,16
8563,O22_1001000408,0,0,1,2
8564,O22_1001000412,0,0,1,2
8635,O4_1001000407,1,4,1,7
8726,O8_1001000412,0,0,1,3
8775,P10_1001000408,1,4,1,9
8847,P13_1001000407,1,6,1,13
8906,P15_1001000412,1,7,1,11
9017,P19_1001000412,1,2,1,7
9090,P21_1001000407,1,4,1,5
9116,P22_1001000407,1,3,1,4
9117,P22_1001000412,1,22,1,40
9248,P6_1001000407,1,2,1,2
9249,P6_1001000408,0,0,1,5
9271,P7_1001000407,1,4,1,4
9323,P9_1001000407,1,2,1,2
9324,P9_1001000408,1,2,1,6

In [6]:
kras_G12C_cov = pd.read_csv('../coverage/out/kras_G12C_coverageByCell.csv')
kras_G12C_cov

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
0,A10_1001000407,0,0,0,0
1,A10_1001000408,0,0,0,0
2,A10_1001000412,0,0,0,0
3,A10_B000863,0,0,0,0
4,A10_B001007,0,0,0,0
5,A10_B001470,0,0,0,0
6,A10_B001474,0,0,0,0
7,A10_B001545,0,0,0,0
8,A10_B001548,0,0,0,0
9,A10_B001554,0,0,0,0
10,A10_B001558,0,0,0,0
11,A10_B002572,0,0,0,0
12,A10_B003070,0,0,0,0
13,A10_B003071,0,0,0,0
14,A10_B003115,0,0,0,0
15,A10_B003125,0,0,0,0
16,A10_B003518,0,0,0,0
17,A10_B003523,0,0,0,0
18,A10_B003527,0,0,0,0
19,A10_B003528,0,0,0,0
20,A10_B003529,0,0,0,0
21,A10_B003588,0,0,0,0
22,A11_1001000407,0,0,0,0
23,A11_1001000408,0,0,0,0
24,A11_1001000412,0,0,0,0
25,A11_B000860,0,0,0,0
26,A11_B000861,0,0,0,0
27,A11_B000862,0,0,0,0
28,A11_B001007,0,0,0,0
29,A11_B001470,0,0,0,0
...,...,...,...,...,...
9318,P8_B003518,0,0,0,0
9319,P8_B003527,0,0,0,0
9320,P8_B003648,0,0,0,0
9321,P8_B003658,0,0,0,0
9322,P8_B003995,0,0,0,0
9323,P9_1001000407,0,0,0,0
9324,P9_1001000408,0,0,0,0
9325,P9_B000281,0,0,0,0
9326,P9_B000419,0,0,0,0
9327,P9_B000861,0,0,0,0
9328,P9_B000862,0,0,0,0
9329,P9_B001007,0,0,0,0
9330,P9_B001470,0,0,0,0
9331,P9_B001475,0,0,0,0
9332,P9_B001543,0,0,0,0
9333,P9_B001545,0,0,0,0
9334,P9_B001548,0,0,0,0
9335,P9_B001554,0,0,0,0
9336,P9_B001558,0,0,0,0
9337,P9_B002573,0,0,0,0
9338,P9_B003067,0,0,0,0
9339,P9_B003071,0,0,0,0
9340,P9_B003187,0,0,0,0
9341,P9_B003518,0,0,0,0
9342,P9_B003527,0,0,0,0
9343,P9_B003528,0,0,0,0
9344,P9_B003577,0,0,0,0
9345,P9_B003656,0,0,0,0
9346,P9_B003658,0,0,0,0
9347,P9_B003995,0,0,0,0

In [7]:
indices = kras_G12C_cov['depth_gvcf'] != 0
kras_G12C_cov_nonZero = kras_G12C_cov[indices]
kras_G12C_cov_nonZero

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
664,B15_B000579,1,52,1,52
691,B15_B003930,1,35,1,35
1508,C3_B000579,1,41,1,41
2316,E10_B003663,1,257,1,257
2321,E11_B000579,1,82,1,82
2393,E14_B000579,1,16,1,16
2398,E14_B002079,1,1,1,1
2665,E2_B000579,1,86,1,86
2874,F10_B003663,1,396,1,396
3059,F16_B003776,1,40,1,40
3598,G15_B000579,1,95,1,95
3817,G22_1001000407,1,6,1,13
4439,H22_1001000408,1,14,1,14
4566,H6_B000863,1,79,1,79
4996,I20_B003125,1,4,1,4
5806,J8_B000580,1,313,1,313
5850,J9_B003663,1,68,1,68
6151,K20_1001000412,1,8,1,10
6341,K6_B001474,1,21,1,21
6882,L3_1001000407,1,8,1,11
7063,M10_B000579,1,38,1,38
7391,M20_B003658,1,136,1,136
7418,M21_B003527,1,2,1,2
8158,N7_B003663,1,112,1,112
8159,N7_B003995,1,38,1,38
8281,O13_B000580,1,145,1,145
8925,P15_B003658,1,174,1,174
9164,P2_B003658,1,117,1,117
9214,P4_B003658,1,190,1,190

In [8]:
braf_V600E_cov = pd.read_csv('../coverage/out/braf_V600E_coverageByCell.csv')
indices = braf_V600E_cov['depth_gvcf'] != 0
braf_V600E_cov_nonZero = braf_V600E_cov[indices]
braf_V600E_cov_nonZero

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
1003,B6_B001545,1,2,1,2
1342,C19_B000420,1,175,1,175
4096,H11_B001548,1,9,1,9
4772,I14_B001007,1,2,1,2
5287,J10_B001548,1,2,1,2
8304,O14_B000420,1,1,1,1

In [9]:
egfr_G719X_cov = pd.read_csv('../coverage/out/egfr_G719X_coverageByCell.csv')
indices = egfr_G719X_cov['depth_gvcf'] != 0
egfr_G719X_cov_nonZero = egfr_G719X_cov[indices]
egfr_G719X_cov_nonZero

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
1291,C17_B003103,1,74,1,74
8003,N22_B002077,1,26,1,26

In [10]:
egfr_L861Q_cov = pd.read_csv('../coverage/out/egfr_L861Q_coverageByCell.csv')
indices = egfr_L861Q_cov['depth_gvcf'] != 0
egfr_L861Q_cov_nonZero = egfr_L861Q_cov[indices]
egfr_L861Q_cov_nonZero

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
1237,C15_B003775,1,10,1,10
1961,D19_B003103,1,92,1,92
5125,I4_B002495,1,82,1,82
7473,M2_B003126,1,44,1,44
8989,P18_1001000407,1,3,1,7

In [11]:
egfr_S768I_cov = pd.read_csv('../coverage/out/egfr_S768I_coverageByCell.csv')
indices = egfr_S768I_cov['depth_gvcf'] != 0
egfr_S768I_cov_nonZero = egfr_S768I_cov[indices]
egfr_S768I_cov_nonZero

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
6783,L20_B003920,1,10,1,10
7336,M19_B003522,1,63,1,63
7865,N18_1001000408,0,0,1,5

In [12]:
egfr_T790M_cov = pd.read_csv('../coverage/out/egfr_T790M_coverageByCell.csv')
indices = egfr_T790M_cov['depth_gvcf'] != 0
egfr_T790M_cov_nonZero = egfr_T790M_cov[indices]
egfr_T790M_cov_nonZero

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
1181,C14_1001000407,1,1,1,3
4666,H9_B003522,1,21,1,21
5979,K15_B001008,1,2,1,2
6182,K21_B001010,1,51,1,51

In [13]:
# this one is wierd...
kras_G13X_cov = pd.read_csv('../coverage/out/kras_G13X_coverageByCell.csv')
kras_G13X_cov
indices = kras_G13X_cov['depth_gvcf'] != '0'
kras_G13X_cov_nonZero = kras_G13X_cov[indices]
kras_G13X_cov_nonZero

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
542,B10_1001000412,1,19,1,29
1216,C15_B001010,1,27,1,27
1399,C20_B001008,1,16,1,16
1815,D14_B003930,1,57,1,57
2365,E13_B001010,1,74,1,74
3925,G5_1001000408,1,14,1,20
4127,H12_B003527,1,25,1,25
4191,H15_1001000412,1,32,1,32
4202,H15_B002079,1,['34'],1,['34']
4289,H17_B003920,1,74,1,74
4308,H18_B003103,1,51,1,51
4819,I15_B003112,1,166,1,166
4956,I1_B000863,1,53,1,53
4980,I20_1001000407,1,17,1,30
5596,J20_B003995,1,36,1,36
5623,J21_B003777,1,2,1,2
6055,K17_B003527,1,55,1,55
6933,L5_B000863,1,49,1,49
7236,M16_B002079,1,4,1,4
7349,M1_B000861,1,545,1,545
7409,M21_B002573,1,3,1,3
7505,M4_1001000407,1,16,1,29
7867,N18_1001000412,1,10,1,21
8181,N8_B003648,1,20,1,20
8474,O19_B003120,1,83,1,83
8900,P14_B003894,1,62,1,62

In [14]:
kras_G13X_cov_nonZero['depth_gvcf'][4202] = 34
kras_G13X_cov_nonZero

/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2862: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
542,B10_1001000412,1,19,1,29
1216,C15_B001010,1,27,1,27
1399,C20_B001008,1,16,1,16
1815,D14_B003930,1,57,1,57
2365,E13_B001010,1,74,1,74
3925,G5_1001000408,1,14,1,20
4127,H12_B003527,1,25,1,25
4191,H15_1001000412,1,32,1,32
4202,H15_B002079,1,['34'],1,34
4289,H17_B003920,1,74,1,74
4308,H18_B003103,1,51,1,51
4819,I15_B003112,1,166,1,166
4956,I1_B000863,1,53,1,53
4980,I20_1001000407,1,17,1,30
5596,J20_B003995,1,36,1,36
5623,J21_B003777,1,2,1,2
6055,K17_B003527,1,55,1,55
6933,L5_B000863,1,49,1,49
7236,M16_B002079,1,4,1,4
7349,M1_B000861,1,545,1,545
7409,M21_B002573,1,3,1,3
7505,M4_1001000407,1,16,1,29
7867,N18_1001000412,1,10,1,21
8181,N8_B003648,1,20,1,20
8474,O19_B003120,1,83,1,83
8900,P14_B003894,1,62,1,62

In [15]:
# this one is wierd too
kras_Q61X_cov = pd.read_csv('../coverage/out/kras_Q61X_coverageByCell.csv')
indices = kras_Q61X_cov['depth_gvcf'] != '0'
kras_Q61X_cov_nonZero = kras_Q61X_cov[indices]
kras_Q61X_cov_nonZero

         cellName  coverage_bool_vcf depth_vcf  coverage_bool_gvcf depth_gvcf
671   B15_B002079                  1        24                   1         24
1827  D15_B002078                  1       137                   1        137
2286   D9_B003577                  1         1                   1          1
2679   E2_B003187                  1       222                   1        222
3331   F4_B003132                  1         7                   1          7
3731  G19_B003654                  1        92                   1         92
6431  L10_B001554                  1    ['92']                   1     ['92']
7322  M19_B000422                  1        12                   1         12
7530   M5_B001470                  1        23                   1         23

In [16]:
kras_Q61X_cov_nonZero['depth_gvcf'][6431] = 92
kras_Q61X_cov_nonZero

/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2862: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

         cellName  coverage_bool_vcf depth_vcf  coverage_bool_gvcf depth_gvcf
671   B15_B002079                  1        24                   1         24
1827  D15_B002078                  1       137                   1        137
2286   D9_B003577                  1         1                   1          1
2679   E2_B003187                  1       222                   1        222
3331   F4_B003132                  1         7                   1          7
3731  G19_B003654                  1        92                   1         92
6431  L10_B001554                  1    ['92']                   1         92
7322  M19_B000422                  1        12                   1         12
7530   M5_B001470                  1        23                   1         23

In [17]:
# fuck why is this so wierd??
egfr_exon19del_cov = pd.read_csv('../coverage/out/egfr_exon19del_coverageByCell.csv')
indices = egfr_exon19del_cov['depth_gvcf'] != '0'
egfr_exon19del_cov_nonZero = egfr_exon19del_cov[indices]
egfr_exon19del_cov_nonZero

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
659,B15_1001000340,1,2,1,2
756,B18_1001000339,1,3,1,3
1013,B6_B003191,1,35,1,35
1366,C19_B003920,1,7,1,7
1508,C3_B000579,1,7,1,7
1531,C4_B001474,1,['21'],1,['21']
1624,C8_1001000340,1,28,1,28
1750,D12_B003776,1,['6'],1,['6']
1754,D13_1001000340,1,7,1,7
1779,D14_1001000339,1,9,1,9
1881,D17_1001000339,1,32,1,32
1939,D18_B003771,1,17,1,17
1945,D19_1001000339,1,3,1,3
2026,D21_1001000340,1,9,1,9
2094,D2_B001464,1,20,1,20
2417,E15_1001000339,1,9,1,9
2497,E17_B003775,1,['31'],1,['31']
2630,E21_B003894,1,22,1,22
2876,F11_1001000407,0,0,1,3
2993,F14_B003771,1,3,1,3
3030,F16_1001000340,1,15,1,15
3059,F16_B003776,1,['11'],1,['11']
3117,F18_B003920,1,36,1,36
3344,F5_B001470,1,['6'],1,['6']
3657,G16_B003894,1,58,1,58
3681,G17_B003775,1,['5'],1,['5']
3790,G20_B003995,1,7,1,7
3810,G21_B003654,1,2,1,2
3846,G22_B003776,1,['14'],1,['14']
3868,G2_B003132,1,14,1,14
...,...,...,...,...,...
5596,J20_B003995,1,44,1,44
5745,J5_B003132,1,9,1,9
5905,K12_B003775,1,['10'],1,['10']
6061,K17_B003894,1,7,1,7
6429,L10_B001475,1,['110'],1,['110']
6572,L15_B003126,1,9,1,9
6784,L20_B003995,1,3,1,3
6877,L2_B003187,1,59,1,59
7002,L7_B003125,1,11,1,11
7156,M13_B003775,1,['2'],1,['2']
7194,M14_B003776,1,['9'],1,['9']
7362,M1_B003132,1,5,1,5
7452,M22_B003920,1,4,1,4
7454,M22_B003995,1,8,1,8
7460,M2_B001470,1,['19'],1,['19']
7716,N13_B001010,1,15,1,15
7943,N20_1001000340,1,10,1,10
8272,O12_B003776,1,['6'],1,['6']
8299,O14_1001000340,1,41,1,41
8332,O14_B003894,1,50,1,50
8401,O17_1001000340,1,21,1,21
8428,O17_B003776,1,['60'],1,['60']
8471,O19_B003103,1,9,1,9
8507,O20_1001000339,1,7,1,7
8561,O22_1001000339,1,18,1,18
8687,O6_B001470,1,['29'],1,['29']
8960,P16_B003995,1,6,1,6
8961,P17_1001000340,1,4,1,4
8987,P17_B003995,1,62,1,62
9144,P2_1001000340,1,12,1,12

In [18]:
# this should fix it
egfr_exon19del_cov_nonZero['depth_gvcf'] = egfr_exon19del_cov_nonZero['depth_gvcf'].str.strip('[')
egfr_exon19del_cov_nonZero['depth_gvcf'] = egfr_exon19del_cov_nonZero['depth_gvcf'].str.strip(']')
egfr_exon19del_cov_nonZero['depth_gvcf'] = egfr_exon19del_cov_nonZero['depth_gvcf'].str.strip("'")
egfr_exon19del_cov_nonZero['depth_gvcf']

/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

659       2
756       3
1013     35
1366      7
1508      7
1531     21
1624     28
1750      6
1754      7
1779      9
1881     32
1939     17
1945      3
2026      9
2094     20
2417      9
2497     31
2630     22
2876      3
2993      3
3030     15
3059     11
3117     36
3344      6
3657     58
3681      5
3790      7
3810      2
3846     14
3868     14
       ...
5596     44
5745      9
5905     10
6061      7
6429    110
6572      9
6784      3
6877     59
7002     11
7156      2
7194      9
7362      5
7452      4
7454      8
7460     19
7716     15
7943     10
8272      6
8299     41
8332     50
8401     21
8428     60
8471      9
8507      7
8561     18
8687     29
8960      6
8961      4
8987     62
9144     12
Name: depth_gvcf, Length: 84, dtype: object

In [19]:
egfr_exon19del_cov_nonZero

,cellName,coverage_bool_vcf,depth_vcf,coverage_bool_gvcf,depth_gvcf
659,B15_1001000340,1,2,1,2
756,B18_1001000339,1,3,1,3
1013,B6_B003191,1,35,1,35
1366,C19_B003920,1,7,1,7
1508,C3_B000579,1,7,1,7
1531,C4_B001474,1,['21'],1,21
1624,C8_1001000340,1,28,1,28
1750,D12_B003776,1,['6'],1,6
1754,D13_1001000340,1,7,1,7
1779,D14_1001000339,1,9,1,9
1881,D17_1001000339,1,32,1,32
1939,D18_B003771,1,17,1,17
1945,D19_1001000339,1,3,1,3
2026,D21_1001000340,1,9,1,9
2094,D2_B001464,1,20,1,20
2417,E15_1001000339,1,9,1,9
2497,E17_B003775,1,['31'],1,31
2630,E21_B003894,1,22,1,22
2876,F11_1001000407,0,0,1,3
2993,F14_B003771,1,3,1,3
3030,F16_1001000340,1,15,1,15
3059,F16_B003776,1,['11'],1,11
3117,F18_B003920,1,36,1,36
3344,F5_B001470,1,['6'],1,6
3657,G16_B003894,1,58,1,58
3681,G17_B003775,1,['5'],1,5
3790,G20_B003995,1,7,1,7
3810,G21_B003654,1,2,1,2
3846,G22_B003776,1,['14'],1,14
3868,G2_B003132,1,14,1,14
...,...,...,...,...,...
5596,J20_B003995,1,44,1,44
5745,J5_B003132,1,9,1,9
5905,K12_B003775,1,['10'],1,10
6061,K17_B003894,1,7,1,7
6429,L10_B001475,1,['110'],1,110
6572,L15_B003126,1,9,1,9
6784,L20_B003995,1,3,1,3
6877,L2_B003187,1,59,1,59
7002,L7_B003125,1,11,1,11
7156,M13_B003775,1,['2'],1,2
7194,M14_B003776,1,['9'],1,9
7362,M1_B003132,1,5,1,5
7452,M22_B003920,1,4,1,4
7454,M22_B003995,1,8,1,8
7460,M2_B001470,1,['19'],1,19
7716,N13_B001010,1,15,1,15
7943,N20_1001000340,1,10,1,10
8272,O12_B003776,1,['6'],1,6
8299,O14_1001000340,1,41,1,41
8332,O14_B003894,1,50,1,50
8401,O17_1001000340,1,21,1,21
8428,O17_B003776,1,['60'],1,60
8471,O19_B003103,1,9,1,9
8507,O20_1001000339,1,7,1,7
8561,O22_1001000339,1,18,1,18
8687,O6_B001470,1,['29'],1,29
8960,P16_B003995,1,6,1,6
8961,P17_1001000340,1,4,1,4
8987,P17_B003995,1,62,1,62
9144,P2_1001000340,1,12,1,12

In [20]:
len(egfr_exon19del_cov_nonZero.index)

84

In [21]:
# thats not good...
egfr_exon20ins_cov = pd.read_csv('../coverage/out/egfr_exon20ins_coverageByCell.csv')
indices = egfr_exon20ins_cov['depth_gvcf'] != 0
egfr_exon20ins_cov_nonZero = egfr_exon20ins_cov[indices]
egfr_exon20ins_cov_nonZero

Empty DataFrame
Columns: [cellName, coverage_bool_vcf, depth_vcf, coverage_bool_gvcf, depth_gvcf]
Index: []

In [22]:
# why are they all 0?? 
set(egfr_exon20ins_cov['depth_gvcf'])

{0}

In [23]:
# set validationTable_cells['coverage_to_ROI']
#    for EGFR L858R
for i in range(0, len(validationTable_cells.index)):
    currCell = validationTable_cells['cell'][i]
    currDriver = validationTable_cells['clinical_driver_gene'][i]
    currMut = validationTable_cells['clinical_mutation'][i]
    
    if currDriver == 'EGFR' and currMut == 'L858R':
        if currCell in list(egfr_L858R_cov_nonZero['cellName']):
            index_cov_nonZero = egfr_L858R_cov_nonZero['cellName'] == currCell
            currRow_cov_nonZero = egfr_L858R_cov_nonZero[index_cov_nonZero]
            currDepth_gvcf = int(currRow_cov_nonZero['depth_gvcf'])
        
            validationTable_cells['coverage_to_ROI'][i] = currDepth_gvcf
        else:
            validationTable_cells['coverage_to_ROI'][i] = 0

/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [45]:
validationTable_cells

,cell,patient,clinical_driver_gene,clinical_mutation,mutations_found,coverage_to_ROI,clinical_mutation_found_bool,tumorCell_bool
0,P13_1001000339,TH169,EGFR,del19,NaN,NaN,0,1
1,C1_B002572,TH266,ALK,fusion,NaN,NaN,0,0
2,J2_B002573,TH266,ALK,fusion,NaN,NaN,0,0
3,P22_B003116,TH231,ALK,fusion,NaN,NaN,0,1
4,O22_B003191,TH226,EGFR,del19,NaN,NaN,0,0
5,J12_B003529,TH171,ALK,fusion,EGFR T903T,NaN,0,1
6,D14_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR T903T, EGFR T629T, EGFR Q787Q",0.0,0,1
7,F14_B003105,TH222,ROS1,fusion,NaN,NaN,0,0
8,P11_1001000340,TH169,EGFR,del19,NaN,NaN,0,1
9,E21_B003930,TH222,ROS1,fusion,EGFR T903T,NaN,0,0
10,N1_B002573,TH266,ALK,fusion,NaN,NaN,0,0
11,C20_B000422,TH238,BRAF,V600E,NaN,NaN,0,0
12,F14_B001007,NaN,NaN,NaN,"EGFR Q787Q, EGFR T629T",NaN,0,0
13,C21_B003920,TH236,EGFR,del19,NaN,NaN,0,0
14,E16_B003894,TH236,EGFR,del19,NaN,NaN,0,0
15,D20_B002097,TH238_Normal,BRAF,V600E,EGFR T903T,NaN,0,0
16,I4_B001558,TH179_Normal,ALK,fusion,NaN,NaN,0,1
17,J14_B002077,TH238,BRAF,V600E,NaN,NaN,0,0
18,L7_B003129,TH226,EGFR,del19,NaN,NaN,0,0
19,C7_B003113,TH218,EGFR,L858R,NaN,0.0,0,0
20,H18_B003116,TH231,ALK,fusion,NaN,NaN,0,0
21,I7_B002572,TH266,ALK,fusion,NaN,NaN,0,0
22,I1_B003187,TH226,EGFR,del19,NaN,NaN,0,0
23,N17_B003776,TH248,EGFR,del19,NaN,NaN,0,1
24,I8_B003659,TH067,EGFR,del19,NaN,NaN,0,0
25,P16_B003126,TH226,EGFR,del19,NaN,NaN,0,0
26,P9_B001007,NaN,NaN,NaN,NaN,NaN,0,0
27,B17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T",9.0,1,1
28,E20_B003646,TH226,EGFR,del19,NaN,NaN,0,0
29,N3_B000861,TH220,ALK,fusion,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...
9851,O15_B003995,TH236,EGFR,del19,NaN,NaN,0,0
9852,F12_B003894,TH236,EGFR,del19,NaN,NaN,0,0
9853,D12_B003771,TH236,EGFR,del19,NaN,NaN,0,0
9854,L21_B002077,TH238,BRAF,V600E,NaN,NaN,0,1
9855,B22_B003920,TH236,EGFR,del19,NaN,NaN,0,0
9856,E22_B003518,TH171,ALK,fusion,NaN,NaN,0,1
9857,N16_B000422,TH238,BRAF,V600E,NaN,NaN,0,0
9858,O12_B001010,NaN,NaN,NaN,NaN,NaN,0,0
9859,H4_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",4.0,1,1
9860,G17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",18.0,1,1
9861,D3_B001559,TH179,BRAF,V600E,KRAS A11A,NaN,0,0
9862,O8_B002572,TH266,ALK,fusion,KRAS K88K,NaN,0,0
9863,C14_B003894,TH236,EGFR,del19,NaN,NaN,0,1
9864,D22_B003775,TH248,EGFR,del19,NaN,NaN,0,0
9865,A15_B000420,TH238,BRAF,V600E,NaN,NaN,0,0
9866,O12_B003776,TH248,EGFR,del19,EGFR del19,NaN,1,1
9867,D14_B002097,TH238_Normal,BRAF,V600E,NaN,NaN,0,0
9868,H12_B002572,TH266,ALK,fusion,NaN,NaN,0,0
9869,A14_B002077,TH238,BRAF,V600E,NaN,NaN,0,0
9870,L9_1001000411,TH185,EGFR,L858R,NaN,0.0,0,1
9871,P9_B003067,TH205,EGFR,L858R,NaN,0.0,0,0
9872,J14_B003518,TH171,ALK,fusion,NaN,NaN,0,1
9873,B20_B000422,TH238,BRAF,V600E,NaN,NaN,0,0
9874,K4_B003187,TH226,EGFR,del19,NaN,NaN,0,0
9875,M17_B003894,TH236,EGFR,del19,NaN,NaN,0,1
9876,O9_B003527,TH171,ALK,fusion,NaN,NaN,0,1
9877,F15_B001008,NaN,NaN,NaN,NaN,NaN,0,0
9878,L20_B003777,TH248,EGFR,del19,NaN,NaN,0,1
9879,O9_1001000407,TH185,EGFR,L858R,EGFR Q787Q,0.0,0,1
9880,L3_B003129,TH226,EGFR,del19,NaN,NaN,0,0

In [46]:
# lets turn this into a function 
def addCoverageFunc(coverage_df, queryGene, queryMutation):
    for i in range(0, len(validationTable_cells.index)):
        currCell = validationTable_cells['cell'][i]
        currDriver = validationTable_cells['clinical_driver_gene'][i]
        currMut = validationTable_cells['clinical_mutation'][i]
    
        if currDriver == queryGene and currMut == queryMutation:
            if currCell in list(coverage_df['cellName']):
                index_cov_nonZero = coverage_df['cellName'] == currCell
                currRow_cov_nonZero = coverage_df[index_cov_nonZero]
                currDepth_gvcf = int(currRow_cov_nonZero['depth_gvcf'])
        
                validationTable_cells['coverage_to_ROI'][i] = currDepth_gvcf
            else:
                validationTable_cells['coverage_to_ROI'][i] = 0

In [47]:
addCoverageFunc(braf_V600E_cov_nonZero, 'BRAF', 'V600E')
addCoverageFunc(egfr_G719X_cov_nonZero, 'EGFR', 'G719X')
addCoverageFunc(egfr_L858R_cov_nonZero, 'EGFR', 'L858R')
addCoverageFunc(egfr_L861Q_cov_nonZero, 'EGFR', 'L861Q')
addCoverageFunc(egfr_S768I_cov_nonZero, 'EGFR', 'S768I')
addCoverageFunc(egfr_T790M_cov_nonZero, 'EGFR', 'T790M')
addCoverageFunc(kras_G12C_cov_nonZero, 'KRAS', 'G12C')
addCoverageFunc(kras_G13X_cov_nonZero, 'KRAS', 'G13X')
addCoverageFunc(kras_Q61X_cov_nonZero, 'KRAS', 'Q61X')
addCoverageFunc(egfr_exon19del_cov_nonZero, 'EGFR', 'del19')
addCoverageFunc(egfr_exon20ins_cov_nonZero, 'EGFR', 'ins20')

/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [48]:
validationTable_cells

,cell,patient,clinical_driver_gene,clinical_mutation,mutations_found,coverage_to_ROI,clinical_mutation_found_bool,tumorCell_bool
0,P13_1001000339,TH169,EGFR,del19,NaN,0.0,0,1
1,C1_B002572,TH266,ALK,fusion,NaN,NaN,0,0
2,J2_B002573,TH266,ALK,fusion,NaN,NaN,0,0
3,P22_B003116,TH231,ALK,fusion,NaN,NaN,0,1
4,O22_B003191,TH226,EGFR,del19,NaN,0.0,0,0
5,J12_B003529,TH171,ALK,fusion,EGFR T903T,NaN,0,1
6,D14_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR T903T, EGFR T629T, EGFR Q787Q",0.0,0,1
7,F14_B003105,TH222,ROS1,fusion,NaN,NaN,0,0
8,P11_1001000340,TH169,EGFR,del19,NaN,0.0,0,1
9,E21_B003930,TH222,ROS1,fusion,EGFR T903T,NaN,0,0
10,N1_B002573,TH266,ALK,fusion,NaN,NaN,0,0
11,C20_B000422,TH238,BRAF,V600E,NaN,0.0,0,0
12,F14_B001007,NaN,NaN,NaN,"EGFR Q787Q, EGFR T629T",NaN,0,0
13,C21_B003920,TH236,EGFR,del19,NaN,0.0,0,0
14,E16_B003894,TH236,EGFR,del19,NaN,0.0,0,0
15,D20_B002097,TH238_Normal,BRAF,V600E,EGFR T903T,0.0,0,0
16,I4_B001558,TH179_Normal,ALK,fusion,NaN,NaN,0,1
17,J14_B002077,TH238,BRAF,V600E,NaN,0.0,0,0
18,L7_B003129,TH226,EGFR,del19,NaN,0.0,0,0
19,C7_B003113,TH218,EGFR,L858R,NaN,0.0,0,0
20,H18_B003116,TH231,ALK,fusion,NaN,NaN,0,0
21,I7_B002572,TH266,ALK,fusion,NaN,NaN,0,0
22,I1_B003187,TH226,EGFR,del19,NaN,0.0,0,0
23,N17_B003776,TH248,EGFR,del19,NaN,0.0,0,1
24,I8_B003659,TH067,EGFR,del19,NaN,0.0,0,0
25,P16_B003126,TH226,EGFR,del19,NaN,0.0,0,0
26,P9_B001007,NaN,NaN,NaN,NaN,NaN,0,0
27,B17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T",9.0,1,1
28,E20_B003646,TH226,EGFR,del19,NaN,0.0,0,0
29,N3_B000861,TH220,ALK,fusion,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...
9851,O15_B003995,TH236,EGFR,del19,NaN,0.0,0,0
9852,F12_B003894,TH236,EGFR,del19,NaN,0.0,0,0
9853,D12_B003771,TH236,EGFR,del19,NaN,0.0,0,0
9854,L21_B002077,TH238,BRAF,V600E,NaN,0.0,0,1
9855,B22_B003920,TH236,EGFR,del19,NaN,0.0,0,0
9856,E22_B003518,TH171,ALK,fusion,NaN,NaN,0,1
9857,N16_B000422,TH238,BRAF,V600E,NaN,0.0,0,0
9858,O12_B001010,NaN,NaN,NaN,NaN,NaN,0,0
9859,H4_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",4.0,1,1
9860,G17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",18.0,1,1
9861,D3_B001559,TH179,BRAF,V600E,KRAS A11A,0.0,0,0
9862,O8_B002572,TH266,ALK,fusion,KRAS K88K,NaN,0,0
9863,C14_B003894,TH236,EGFR,del19,NaN,0.0,0,1
9864,D22_B003775,TH248,EGFR,del19,NaN,0.0,0,0
9865,A15_B000420,TH238,BRAF,V600E,NaN,0.0,0,0
9866,O12_B003776,TH248,EGFR,del19,EGFR del19,6.0,1,1
9867,D14_B002097,TH238_Normal,BRAF,V600E,NaN,0.0,0,0
9868,H12_B002572,TH266,ALK,fusion,NaN,NaN,0,0
9869,A14_B002077,TH238,BRAF,V600E,NaN,0.0,0,0
9870,L9_1001000411,TH185,EGFR,L858R,NaN,0.0,0,1
9871,P9_B003067,TH205,EGFR,L858R,NaN,0.0,0,0
9872,J14_B003518,TH171,ALK,fusion,NaN,NaN,0,1
9873,B20_B000422,TH238,BRAF,V600E,NaN,0.0,0,0
9874,K4_B003187,TH226,EGFR,del19,NaN,0.0,0,0
9875,M17_B003894,TH236,EGFR,del19,NaN,0.0,0,1
9876,O9_B003527,TH171,ALK,fusion,NaN,NaN,0,1
9877,F15_B001008,NaN,NaN,NaN,NaN,NaN,0,0
9878,L20_B003777,TH248,EGFR,del19,NaN,0.0,0,1
9879,O9_1001000407,TH185,EGFR,L858R,EGFR Q787Q,0.0,0,1
9880,L3_B003129,TH226,EGFR,del19,NaN,0.0,0,0

In [49]:
# why isnt this working?? 
set(validationTable_cells['coverage_to_ROI'])

{0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 9.0,
 nan,
 nan,
 14.0,
 2.0,
 16.0,
 10.0,
 3.0,
 4.0,
 13.0,
 19.0,
 23.0,
 24.0,
 5.0,
 18.0,
 21.0,
 29.0,
 28.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 35.0,
 7.0,
 38.0,
 40.0,
 41.0,
 8.0,
 44.0,
 48.0,
 50.0,
 52.0,
 11.0,
 58.0,
 59.0,
 60.0,
 12.0,
 62.0,
 68.0,
 73.0,
 15.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 82.0,
 nan,
 nan,
 nan,
 17.0,
 86.0,
 nan,
 nan,
 nan,
 nan,
 95.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 110.0,
 22.0,
 nan,
 nan,
 nan,
 nan,
 112.0,
 117.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 136.0,
 nan,
 nan,
 nan,
 26.0,
 145.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 32.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 33.0,
 nan,
 175.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 36.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 257.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 313.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 396.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 174.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 190.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 ...}

In [50]:
# total num cells with coverage?
indices = validationTable_cells['coverage_to_ROI'] != 0
validationTable_cells_sub = validationTable_cells[indices]
validationTable_cells_sub

,cell,patient,clinical_driver_gene,clinical_mutation,mutations_found,coverage_to_ROI,clinical_mutation_found_bool,tumorCell_bool
1,C1_B002572,TH266,ALK,fusion,NaN,NaN,0,0
2,J2_B002573,TH266,ALK,fusion,NaN,NaN,0,0
3,P22_B003116,TH231,ALK,fusion,NaN,NaN,0,1
5,J12_B003529,TH171,ALK,fusion,EGFR T903T,NaN,0,1
7,F14_B003105,TH222,ROS1,fusion,NaN,NaN,0,0
9,E21_B003930,TH222,ROS1,fusion,EGFR T903T,NaN,0,0
10,N1_B002573,TH266,ALK,fusion,NaN,NaN,0,0
12,F14_B001007,NaN,NaN,NaN,"EGFR Q787Q, EGFR T629T",NaN,0,0
16,I4_B001558,TH179_Normal,ALK,fusion,NaN,NaN,0,1
20,H18_B003116,TH231,ALK,fusion,NaN,NaN,0,0
21,I7_B002572,TH266,ALK,fusion,NaN,NaN,0,0
26,P9_B001007,NaN,NaN,NaN,NaN,NaN,0,0
27,B17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T",9.0,1,1
29,N3_B000861,TH220,ALK,fusion,NaN,NaN,0,0
32,L14_B001016,NaN,NaN,NaN,NaN,NaN,0,0
34,F9_B003527,TH171,ALK,fusion,NaN,NaN,0,1
38,K18_B003527,TH171,ALK,fusion,NaN,NaN,0,0
41,J20_B003518,TH171,ALK,fusion,NaN,NaN,0,1
48,H11_B001548,TH179,BRAF,V600E,NaN,9.0,0,1
49,L11_B003588,TH171,ALK,fusion,NaN,NaN,0,1
50,D6_1001000378,TH146,ROS1,ROS1-CD74,NaN,NaN,0,0
54,G2_1001000317,TH103,ALK,fusion,NaN,NaN,0,1
57,G9_B003119,TH231,ALK,fusion,NaN,NaN,0,0
59,D14_B002572,TH266,ALK,fusion,NaN,NaN,0,0
61,K15_B003930,TH222,ROS1,fusion,NaN,NaN,0,0
64,J14_B003116,TH231,ALK,fusion,ROS1 fusion,NaN,0,1
67,L5_1001000408,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",14.0,1,1
69,B21_B003518,TH171,ALK,fusion,NaN,NaN,0,1
70,O1_B002571,TH266,ALK,fusion,NaN,NaN,0,0
71,P22_B001010,NaN,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...
9806,E3_B001007,NaN,NaN,NaN,NaN,NaN,0,0
9807,C4_B001007,NaN,NaN,NaN,NaN,NaN,0,0
9812,B22_B002572,TH266,ALK,fusion,NaN,NaN,0,0
9813,N16_B001010,NaN,NaN,NaN,NaN,NaN,0,0
9815,F11_B002573,TH266,ALK,fusion,NaN,NaN,0,0
9816,N6_B000862,TH220,ALK,fusion,EGFR T629T,NaN,0,1
9817,K21_B003116,TH231,ALK,fusion,NaN,NaN,0,0
9822,F10_B002572,TH266,ALK,fusion,NaN,NaN,0,0
9828,N9_B001007,NaN,NaN,NaN,NaN,NaN,0,0
9829,A19_B003522,TH171,ALK,fusion,NaN,NaN,0,0
9830,F8_B000863,TH220,ALK,fusion,NaN,NaN,0,1
9832,N18_B003529,TH171,ALK,fusion,NaN,NaN,0,0
9833,E9_B003522,TH171,ALK,fusion,EGFR T903T,NaN,0,1
9835,O7_B003518,TH171,ALK,fusion,NaN,NaN,0,1
9837,B5_1001000412,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",6.0,1,1
9838,F20_B001010,NaN,NaN,NaN,NaN,NaN,0,0
9840,E1_B001007,NaN,NaN,NaN,NaN,NaN,0,0
9842,F3_B002573,TH266,ALK,fusion,"KRAS G12C, KRAS G12F",NaN,0,0
9846,L1_B003119,TH231,ALK,fusion,NaN,NaN,0,0
9850,H15_B003120,TH231,ALK,fusion,NaN,NaN,0,0
9856,E22_B003518,TH171,ALK,fusion,NaN,NaN,0,1
9858,O12_B001010,NaN,NaN,NaN,NaN,NaN,0,0
9859,H4_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",4.0,1,1
9860,G17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",18.0,1,1
9862,O8_B002572,TH266,ALK,fusion,KRAS K88K,NaN,0,0
9866,O12_B003776,TH248,EGFR,del19,EGFR del19,6.0,1,1
9868,H12_B002572,TH266,ALK,fusion,NaN,NaN,0,0
9872,J14_B003518,TH171,ALK,fusion,NaN,NaN,0,1
9876,O9_B003527,TH171,ALK,fusion,NaN,NaN,0,1
9877,F15_B001008,NaN,NaN,NaN,NaN,NaN,0,0

In [51]:
# reindex
validationTable_cells_sub = validationTable_cells_sub.reset_index(drop=True)
validationTable_cells_sub

,cell,patient,clinical_driver_gene,clinical_mutation,mutations_found,coverage_to_ROI,clinical_mutation_found_bool,tumorCell_bool
0,C1_B002572,TH266,ALK,fusion,NaN,NaN,0,0
1,J2_B002573,TH266,ALK,fusion,NaN,NaN,0,0
2,P22_B003116,TH231,ALK,fusion,NaN,NaN,0,1
3,J12_B003529,TH171,ALK,fusion,EGFR T903T,NaN,0,1
4,F14_B003105,TH222,ROS1,fusion,NaN,NaN,0,0
5,E21_B003930,TH222,ROS1,fusion,EGFR T903T,NaN,0,0
6,N1_B002573,TH266,ALK,fusion,NaN,NaN,0,0
7,F14_B001007,NaN,NaN,NaN,"EGFR Q787Q, EGFR T629T",NaN,0,0
8,I4_B001558,TH179_Normal,ALK,fusion,NaN,NaN,0,1
9,H18_B003116,TH231,ALK,fusion,NaN,NaN,0,0
10,I7_B002572,TH266,ALK,fusion,NaN,NaN,0,0
11,P9_B001007,NaN,NaN,NaN,NaN,NaN,0,0
12,B17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T",9.0,1,1
13,N3_B000861,TH220,ALK,fusion,NaN,NaN,0,0
14,L14_B001016,NaN,NaN,NaN,NaN,NaN,0,0
15,F9_B003527,TH171,ALK,fusion,NaN,NaN,0,1
16,K18_B003527,TH171,ALK,fusion,NaN,NaN,0,0
17,J20_B003518,TH171,ALK,fusion,NaN,NaN,0,1
18,H11_B001548,TH179,BRAF,V600E,NaN,9.0,0,1
19,L11_B003588,TH171,ALK,fusion,NaN,NaN,0,1
20,D6_1001000378,TH146,ROS1,ROS1-CD74,NaN,NaN,0,0
21,G2_1001000317,TH103,ALK,fusion,NaN,NaN,0,1
22,G9_B003119,TH231,ALK,fusion,NaN,NaN,0,0
23,D14_B002572,TH266,ALK,fusion,NaN,NaN,0,0
24,K15_B003930,TH222,ROS1,fusion,NaN,NaN,0,0
25,J14_B003116,TH231,ALK,fusion,ROS1 fusion,NaN,0,1
26,L5_1001000408,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",14.0,1,1
27,B21_B003518,TH171,ALK,fusion,NaN,NaN,0,1
28,O1_B002571,TH266,ALK,fusion,NaN,NaN,0,0
29,P22_B001010,NaN,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...
3888,E3_B001007,NaN,NaN,NaN,NaN,NaN,0,0
3889,C4_B001007,NaN,NaN,NaN,NaN,NaN,0,0
3890,B22_B002572,TH266,ALK,fusion,NaN,NaN,0,0
3891,N16_B001010,NaN,NaN,NaN,NaN,NaN,0,0
3892,F11_B002573,TH266,ALK,fusion,NaN,NaN,0,0
3893,N6_B000862,TH220,ALK,fusion,EGFR T629T,NaN,0,1
3894,K21_B003116,TH231,ALK,fusion,NaN,NaN,0,0
3895,F10_B002572,TH266,ALK,fusion,NaN,NaN,0,0
3896,N9_B001007,NaN,NaN,NaN,NaN,NaN,0,0
3897,A19_B003522,TH171,ALK,fusion,NaN,NaN,0,0
3898,F8_B000863,TH220,ALK,fusion,NaN,NaN,0,1
3899,N18_B003529,TH171,ALK,fusion,NaN,NaN,0,0
3900,E9_B003522,TH171,ALK,fusion,EGFR T903T,NaN,0,1
3901,O7_B003518,TH171,ALK,fusion,NaN,NaN,0,1
3902,B5_1001000412,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",6.0,1,1
3903,F20_B001010,NaN,NaN,NaN,NaN,NaN,0,0
3904,E1_B001007,NaN,NaN,NaN,NaN,NaN,0,0
3905,F3_B002573,TH266,ALK,fusion,"KRAS G12C, KRAS G12F",NaN,0,0
3906,L1_B003119,TH231,ALK,fusion,NaN,NaN,0,0
3907,H15_B003120,TH231,ALK,fusion,NaN,NaN,0,0
3908,E22_B003518,TH171,ALK,fusion,NaN,NaN,0,1
3909,O12_B001010,NaN,NaN,NaN,NaN,NaN,0,0
3910,H4_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",4.0,1,1
3911,G17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",18.0,1,1
3912,O8_B002572,TH266,ALK,fusion,KRAS K88K,NaN,0,0
3913,O12_B003776,TH248,EGFR,del19,EGFR del19,6.0,1,1
3914,H12_B002572,TH266,ALK,fusion,NaN,NaN,0,0
3915,J14_B003518,TH171,ALK,fusion,NaN,NaN,0,1
3916,O9_B003527,TH171,ALK,fusion,NaN,NaN,0,1
3917,F15_B001008,NaN,NaN,NaN,NaN,NaN,0,0

In [52]:
import math
myList = []
for i in range(0, len(validationTable_cells_sub.index)):
    curr = validationTable_cells_sub['coverage_to_ROI'][i]
    if not math.isnan(curr):
        myList.append(True)
    else:
        myList.append(False)

In [53]:
type(myList)

list

In [54]:
type(indices)

pandas.core.series.Series

In [55]:
myList1 = pd.Series(myList)
myList1

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12       True
13      False
14      False
15      False
16      False
17      False
18       True
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26       True
27      False
28      False
29      False
        ...
3888    False
3889    False
3890    False
3891    False
3892    False
3893    False
3894    False
3895    False
3896    False
3897    False
3898    False
3899    False
3900    False
3901    False
3902     True
3903    False
3904    False
3905    False
3906    False
3907    False
3908    False
3909    False
3910     True
3911     True
3912    False
3913     True
3914    False
3915    False
3916    False
3917    False
Length: 3918, dtype: bool

In [56]:
# fuck yeah this works
#    so only 243 cells with coverage to their ROI!!
validationTable_cells_sub[myList1]

,cell,patient,clinical_driver_gene,clinical_mutation,mutations_found,coverage_to_ROI,clinical_mutation_found_bool,tumorCell_bool
12,B17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T",9.0,1,1
18,H11_B001548,TH179,BRAF,V600E,NaN,9.0,0,1
26,L5_1001000408,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",14.0,1,1
42,M22_B003920,TH236,EGFR,del19,"EGFR Q787Q, EGFR del19, EGFR del19",4.0,1,1
71,G5_1001000412,TH185,EGFR,L858R,"EGFR R521K, EGFR T629T",2.0,0,1
101,G18_1001000407,TH185,EGFR,L858R,EGFR Q787Q,2.0,0,1
108,F14_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",16.0,1,1
115,F6_1001000408,TH185,EGFR,L858R,"EGFR R521K, EGFR T903T, EGFR T629T, EGFR Q787Q",2.0,0,1
120,C22_1001000408,TH185,EGFR,L858R,"EGFR L858R, EGFR T903T, EGFR T629T, EGFR Q787Q",2.0,1,1
134,D21_1001000340,TH169,EGFR,del19,"EGFR del19, EGFR del19",9.0,1,1
135,L7_1001000408,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",10.0,1,1
141,P6_1001000408,TH185,EGFR,L858R,NaN,5.0,0,1
152,O8_1001000412,TH185,EGFR,L858R,EGFR R521K,3.0,0,1
160,J15_1001000412,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",5.0,1,1
179,D10_1001000407,TH185,EGFR,L858R,EGFR L858R,2.0,1,1
181,G16_B003894,TH236,EGFR,del19,"EGFR Q787Q, EGFR T903T, EGFR del19, EGFR del19",58.0,1,1
187,L13_1001000408,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",16.0,1,1
191,M21_1001000407,TH185,EGFR,L858R,"EGFR L858R, EGFR T903T",13.0,1,1
199,B6_B003191,TH226,EGFR,del19,"EGFR del19, EGFR T903T, EGFR del19, EGFR Q787Q",35.0,1,1
212,M13_B003775,TH248,EGFR,del19,"EGFR T903T, EGFR T629T, EGFR del19, EGFR Q787Q...",2.0,1,1
217,K12_1001000412,TH185,EGFR,L858R,"EGFR T903T, EGFR Q787Q",2.0,0,1
221,M7_1001000412,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T629T, EGFR Q787Q",7.0,1,1
243,I21_B003777,TH248,EGFR,del19,EGFR del19,3.0,1,1
278,B22_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T629T",19.0,1,1
289,H15_B003776,TH248,EGFR,del19,"EGFR del19, EGFR T903T, EGFR Q787Q",31.0,1,1
295,P17_B003995,TH236,EGFR,del19,"EGFR del19, EGFR del19, EGFR Q787Q",62.0,1,1
298,H1_B003191,TH226,EGFR,del19,"EGFR R521K, EGFR del19, EGFR T903T, EGFR T629T...",38.0,1,1
309,G17_B003775,TH248,EGFR,del19,"EGFR del19, EGFR Q787Q",5.0,1,1
361,G9_B001475,TH248,EGFR,del19,"EGFR T903T, EGFR T629T, EGFR del19, EGFR Q787Q",73.0,1,1
362,E21_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",11.0,1,1
...,...,...,...,...,...,...,...,...
3577,J4_1001000408,TH185,EGFR,L858R,EGFR Q787Q,3.0,0,1
3583,C22_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",6.0,1,1
3585,N19_1001000407,TH185,EGFR,L858R,"EGFR L858R, EGFR T629T, EGFR Q787Q",12.0,1,1
3595,M20_1001000408,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR Q787Q",18.0,1,1
3604,L11_1001000407,TH185,EGFR,L858R,"EGFR T903T, EGFR Q787Q",13.0,0,1
3610,N7_B003663,TH225,KRAS,G12C,EGFR T903T,112.0,0,1
3634,O10_1001000407,TH185,EGFR,L858R,"EGFR L858R, EGFR T903T",3.0,1,1
3648,B13_1001000412,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",4.0,1,1
3650,L5_1001000412,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",6.0,1,1
3729,K5_1001000412,TH185,EGFR,L858R,"EGFR R521K, EGFR T903T, EGFR T629T, EGFR Q787Q",7.0,0,1
3737,B15_B000579,TH225,KRAS,G12C,"EGFR R521K, EGFR Q787Q",52.0,0,1
3750,M11_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T629T, EGFR Q787Q",8.0,1,1
3755,L17_1001000408,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T629T, EGFR Q787Q",10.0,1,1
3769,E14_1001000407,TH185,EGFR,L858R,NaN,3.0,0,1
3773,E4_1001000412,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",19.0,1,1
3793,F18_B003920,TH236,EGFR,del19,"EGFR del19, EGFR T903T, EGFR del19",36.0,1,1
3820,B18_1001000339,TH169,EGFR,del19,"EGFR R521K, EGFR del19, EGFR del19",3.0,1,1
3822,D5_1001000411,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",11.0,1,1
3825,F10_1001000407,TH185,EGFR,L858R,EGFR L858R,10.0,1,1
3833,B13_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR T903T, EGFR Q787Q",6.0,0,1
3836,E9_1001000412,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T629T, EGFR Q787Q",11.0,1,1
3844,G20_B003995,TH236,EGFR,del19,"EGFR Q787Q, EGFR T903T, EGFR del19, EGFR del19",7.0,1,1
3848,H18_1001000412,TH185,EGFR,L858R,"EGFR L858R, EGFR T903T",6.0,1,1
3859,K12_B003775,TH248,EGFR,del19,EGFR del19,10.0,1,1
3870,P17_1001000340,TH169,EGFR,del19,"EGFR R521K, EGFR del19, EGFR T629T, EGFR del19",4.0,1,1
3873,F5_B001470,TH248,EGFR,del19,EGFR del19,6.0,1,1
3902,B5_1001000412,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",6.0,1,1
3910,H4_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",4.0,1,1
3911,G17_1001000407,TH185,EGFR,L858R,"EGFR R521K, EGFR L858R, EGFR T903T, EGFR T629T...",18.0,1,1
3913,O12_B003776,TH248,EGFR,del19,EGFR del19,6.0,1,1

In [57]:
#/////////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////////
#
# NOW ADD TO VALIDATIONTABLE_PATIENTS
#
#/////////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////////

In [58]:
coverageDict = {}

In [59]:
patientsList = validationTable_patients['patient']
patientsList

0            TH248
1            TH205
2            TH217
3            TH185
4            TH218
5            TH172
6            TH226
7            TH174
8            TH231
9     TH179_Normal
10           TH171
11           TH227
12           TH222
13           TH220
14           TH158
15           TH223
16           TH156
17           TH183
18           TH155
19           TH236
20           TH146
21           TH179
22           TH157
23           TH169
24           TH225
25           TH103
26           TH238
27           TH067
28           TH199
29           TH266
30           TH150
31           TH210
32           TH208
33           TH107
34    TH238_Normal
Name: patient, dtype: object

In [60]:
for item in patientsList:
    coverageDict.update({item:0})

In [61]:
coverageDict

{'TH067': 0,
 'TH103': 0,
 'TH107': 0,
 'TH146': 0,
 'TH150': 0,
 'TH155': 0,
 'TH156': 0,
 'TH157': 0,
 'TH158': 0,
 'TH169': 0,
 'TH171': 0,
 'TH172': 0,
 'TH174': 0,
 'TH179': 0,
 'TH179_Normal': 0,
 'TH183': 0,
 'TH185': 0,
 'TH199': 0,
 'TH205': 0,
 'TH208': 0,
 'TH210': 0,
 'TH217': 0,
 'TH218': 0,
 'TH220': 0,
 'TH222': 0,
 'TH223': 0,
 'TH225': 0,
 'TH226': 0,
 'TH227': 0,
 'TH231': 0,
 'TH236': 0,
 'TH238': 0,
 'TH238_Normal': 0,
 'TH248': 0,
 'TH266': 0}

In [67]:
import math
for i in range(0, len(validationTable_cells.index)):
    currCell = validationTable_cells['cell'][i]
    currPatient = validationTable_cells['patient'][i]
    
    if currPatient in coverageDict:
        currDictVal = coverageDict[currPatient]
        currCoverage = float(validationTable_cells['coverage_to_ROI'][i])
    
        if not math.isnan(currCoverage) and currCoverage != 0:
            updateVal = currDictVal + 1
            coverageDict.update({currPatient:updateVal})
            #print(currCoverage)

In [68]:
# FUCK this is sparse
coverageDict

{'TH067': 0,
 'TH103': 0,
 'TH107': 0,
 'TH146': 0,
 'TH150': 0,
 'TH155': 0,
 'TH156': 0,
 'TH157': 0,
 'TH158': 0,
 'TH169': 24,
 'TH171': 0,
 'TH172': 0,
 'TH174': 0,
 'TH179': 4,
 'TH179_Normal': 0,
 'TH183': 0,
 'TH185': 198,
 'TH199': 0,
 'TH205': 1,
 'TH208': 1,
 'TH210': 0,
 'TH217': 0,
 'TH218': 0,
 'TH220': 0,
 'TH222': 0,
 'TH223': 0,
 'TH225': 17,
 'TH226': 10,
 'TH227': 0,
 'TH231': 0,
 'TH236': 19,
 'TH238': 2,
 'TH238_Normal': 0,
 'TH248': 21,
 'TH266': 0}

In [69]:
validationTable_patients

,patient,driver_gene,driver_mutation,mutations_found,numCells,numTumorCells,numTumorCells_w_coverage_to_ROI,numTumorCells_clinMut_found
0,TH248,EGFR,del19,"EGFR Q787Q,EGFR Q787Q,EGFR T903T,EGFR T903T,EG...",NaN,384,NaN,20
1,TH205,EGFR,L858R,"['ROS1 fusion', 'NTRK fusion', 'EGFR L858R', '...",NaN,9,NaN,0
2,TH217,EGFR,del19,[],NaN,4,NaN,0
3,TH185,EGFR,L858R,"['EGFR R521K', 'EGFR Q787Q', 'EGFR V536M', 'KR...",NaN,952,NaN,145
4,TH218,EGFR,L858R,"['EGFR P589L', 'BRAF G643G', 'EGFR T629T', 'EG...",NaN,11,NaN,0
5,TH172,BRAF,V600E,"['EGFR R521K', 'EGFR Q787Q', 'EGFR T629T']",NaN,0,NaN,0
6,TH226,EGFR,del19,"['ROS1 fusion', 'NTRK fusion', 'EGFR R1100S', ...",NaN,205,NaN,10
7,TH174,WT,NaN,[],NaN,0,NaN,0
8,TH231,ALK,fusion,"['ROS1 fusion', 'EGFR R521K', 'EML4 fusion', '...",NaN,353,NaN,1
9,TH179_Normal,ALK,fusion,"['EGFR T903T', 'BRAF G643G', 'EGFR Q787Q']",NaN,11,NaN,0
10,TH171,ALK,fusion,"['ALK-EML4 fusion', 'BRAF G469R', 'EGFR V1142V...",NaN,720,NaN,3
11,TH227,ALK,intron 19 rearrangement,"['EGFR T629T', 'EGFR R521K', 'EGFR Q787Q', 'EG...",NaN,17,NaN,0
12,TH222,ROS1,fusion,"['EGFR L1034I', 'EGFR R1100S', 'BRAF G643G', '...",NaN,7,NaN,0
13,TH220,ALK,fusion,"['ALK-EML4 fusion', 'EGFR T629T', 'BRAF G643G'...",NaN,107,NaN,3
14,TH158,EGFR,del19,"['KRAS A11A', 'BRAF R682W', 'KRAS G12C']",NaN,3,NaN,0
15,TH223,EGFR,del19,"['EGFR T903T', 'BRAF G643G']",NaN,7,NaN,0
16,TH156,ALK,fusion,[],NaN,0,NaN,0
17,TH183,EGFR,del19,[],NaN,0,NaN,0
18,TH155,EGFR,del19,[],NaN,0,NaN,0
19,TH236,EGFR,del19,"['EGFR K754E', 'EGFR R1100S', 'EGFR P1019L', '...",NaN,101,NaN,18
20,TH146,ROS1,ROS1-CD74,['ROS1 fusion'],NaN,0,NaN,0
21,TH179,BRAF,V600E,"['BRAF G466E', 'EGFR Q787Q', 'KRAS C118S', 'KR...",NaN,137,NaN,0
22,TH157,ALK,fusion,[],NaN,0,NaN,0
23,TH169,EGFR,del19,"['EGFR T629T', 'EGFR R521K', 'KRAS A11A', 'ALK...",NaN,178,NaN,23
24,TH225,KRAS,G12C,"['EGFR T629T', 'EGFR R521K', 'EGFR Q787Q', 'EG...",NaN,20,NaN,0
25,TH103,ALK,fusion,"['ALK-EML4 fusion', 'ROS1 fusion', 'EGFR T629T...",NaN,65,NaN,4
26,TH238,BRAF,V600E,"['EGFR P589L', 'EGFR T629T', 'KRAS G13V', 'EGF...",NaN,260,NaN,0
27,TH067,EGFR,del19,"['ROS1 fusion', 'BRAF G643G', 'EML4 fusion', '...",NaN,97,NaN,0
28,TH199,KRAS,G12C,[],NaN,0,NaN,0
29,TH266,ALK,fusion,"['ALK-EML4 fusion', 'ROS1 fusion', 'KRAS K88K'...",NaN,1,NaN,0
30,TH150,WT,NaN,[],NaN,0,NaN,0
31,TH210,ALK,fusion,"['EGFR T903T', 'BRAF G643G']",NaN,15,NaN,0
32,TH208,EGFR,L861Q,"['EGFR T629T', 'EGFR R521K', 'EGFR L861Q', 'EG...",NaN,1,NaN,1
33,TH107,EGFR,del19,['KRAS G12C'],NaN,0,NaN,0
34,TH238_Normal,BRAF,V600E,"['NTRK fusion', 'EGFR T629T', 'EGFR R521K', 'E...",NaN,4,NaN,0

In [70]:
len(coverageDict)

35

In [71]:
coverageDict.values()

dict_values([21, 1, 0, 198, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0, 4, 0, 24, 17, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0])

In [72]:
validationTable_patients['numTumorCells_w_coverage_to_ROI'] = coverageDict.values()
validationTable_patients

,patient,driver_gene,driver_mutation,mutations_found,numCells,numTumorCells,numTumorCells_w_coverage_to_ROI,numTumorCells_clinMut_found
0,TH248,EGFR,del19,"EGFR Q787Q,EGFR Q787Q,EGFR T903T,EGFR T903T,EG...",NaN,384,21,20
1,TH205,EGFR,L858R,"['ROS1 fusion', 'NTRK fusion', 'EGFR L858R', '...",NaN,9,1,0
2,TH217,EGFR,del19,[],NaN,4,0,0
3,TH185,EGFR,L858R,"['EGFR R521K', 'EGFR Q787Q', 'EGFR V536M', 'KR...",NaN,952,198,145
4,TH218,EGFR,L858R,"['EGFR P589L', 'BRAF G643G', 'EGFR T629T', 'EG...",NaN,11,0,0
5,TH172,BRAF,V600E,"['EGFR R521K', 'EGFR Q787Q', 'EGFR T629T']",NaN,0,0,0
6,TH226,EGFR,del19,"['ROS1 fusion', 'NTRK fusion', 'EGFR R1100S', ...",NaN,205,10,10
7,TH174,WT,NaN,[],NaN,0,0,0
8,TH231,ALK,fusion,"['ROS1 fusion', 'EGFR R521K', 'EML4 fusion', '...",NaN,353,0,1
9,TH179_Normal,ALK,fusion,"['EGFR T903T', 'BRAF G643G', 'EGFR Q787Q']",NaN,11,0,0
10,TH171,ALK,fusion,"['ALK-EML4 fusion', 'BRAF G469R', 'EGFR V1142V...",NaN,720,0,3
11,TH227,ALK,intron 19 rearrangement,"['EGFR T629T', 'EGFR R521K', 'EGFR Q787Q', 'EG...",NaN,17,0,0
12,TH222,ROS1,fusion,"['EGFR L1034I', 'EGFR R1100S', 'BRAF G643G', '...",NaN,7,0,0
13,TH220,ALK,fusion,"['ALK-EML4 fusion', 'EGFR T629T', 'BRAF G643G'...",NaN,107,0,3
14,TH158,EGFR,del19,"['KRAS A11A', 'BRAF R682W', 'KRAS G12C']",NaN,3,0,0
15,TH223,EGFR,del19,"['EGFR T903T', 'BRAF G643G']",NaN,7,0,0
16,TH156,ALK,fusion,[],NaN,0,0,0
17,TH183,EGFR,del19,[],NaN,0,0,0
18,TH155,EGFR,del19,[],NaN,0,0,0
19,TH236,EGFR,del19,"['EGFR K754E', 'EGFR R1100S', 'EGFR P1019L', '...",NaN,101,19,18
20,TH146,ROS1,ROS1-CD74,['ROS1 fusion'],NaN,0,0,0
21,TH179,BRAF,V600E,"['BRAF G466E', 'EGFR Q787Q', 'KRAS C118S', 'KR...",NaN,137,4,0
22,TH157,ALK,fusion,[],NaN,0,0,0
23,TH169,EGFR,del19,"['EGFR T629T', 'EGFR R521K', 'KRAS A11A', 'ALK...",NaN,178,24,23
24,TH225,KRAS,G12C,"['EGFR T629T', 'EGFR R521K', 'EGFR Q787Q', 'EG...",NaN,20,17,0
25,TH103,ALK,fusion,"['ALK-EML4 fusion', 'ROS1 fusion', 'EGFR T629T...",NaN,65,0,4
26,TH238,BRAF,V600E,"['EGFR P589L', 'EGFR T629T', 'KRAS G13V', 'EGF...",NaN,260,2,0
27,TH067,EGFR,del19,"['ROS1 fusion', 'BRAF G643G', 'EML4 fusion', '...",NaN,97,0,0
28,TH199,KRAS,G12C,[],NaN,0,0,0
29,TH266,ALK,fusion,"['ALK-EML4 fusion', 'ROS1 fusion', 'KRAS K88K'...",NaN,1,0,0
30,TH150,WT,NaN,[],NaN,0,0,0
31,TH210,ALK,fusion,"['EGFR T903T', 'BRAF G643G']",NaN,15,0,0
32,TH208,EGFR,L861Q,"['EGFR T629T', 'EGFR R521K', 'EGFR L861Q', 'EG...",NaN,1,1,1
33,TH107,EGFR,del19,['KRAS G12C'],NaN,0,0,0
34,TH238_Normal,BRAF,V600E,"['NTRK fusion', 'EGFR T629T', 'EGFR R521K', 'E...",NaN,4,0,0

In [73]:
#/////////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////////
#
# LETS ADD NUM_CELLS COL
#
#/////////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////////

In [74]:
# this dictionary thing worked well
numCellsDict = {}

In [75]:
patientsList = validationTable_patients['patient']
patientsList

0            TH248
1            TH205
2            TH217
3            TH185
4            TH218
5            TH172
6            TH226
7            TH174
8            TH231
9     TH179_Normal
10           TH171
11           TH227
12           TH222
13           TH220
14           TH158
15           TH223
16           TH156
17           TH183
18           TH155
19           TH236
20           TH146
21           TH179
22           TH157
23           TH169
24           TH225
25           TH103
26           TH238
27           TH067
28           TH199
29           TH266
30           TH150
31           TH210
32           TH208
33           TH107
34    TH238_Normal
Name: patient, dtype: object

In [76]:
for item in patientsList:
    numCellsDict.update({item:0})

In [77]:
numCellsDict

{'TH067': 0,
 'TH103': 0,
 'TH107': 0,
 'TH146': 0,
 'TH150': 0,
 'TH155': 0,
 'TH156': 0,
 'TH157': 0,
 'TH158': 0,
 'TH169': 0,
 'TH171': 0,
 'TH172': 0,
 'TH174': 0,
 'TH179': 0,
 'TH179_Normal': 0,
 'TH183': 0,
 'TH185': 0,
 'TH199': 0,
 'TH205': 0,
 'TH208': 0,
 'TH210': 0,
 'TH217': 0,
 'TH218': 0,
 'TH220': 0,
 'TH222': 0,
 'TH223': 0,
 'TH225': 0,
 'TH226': 0,
 'TH227': 0,
 'TH231': 0,
 'TH236': 0,
 'TH238': 0,
 'TH238_Normal': 0,
 'TH248': 0,
 'TH266': 0}

In [78]:
# fill it in 
for i in range(0, len(validationTable_cells.index)):
    currCell = validationTable_cells['cell'][i]
    currPatient = validationTable_cells['patient'][i]
    
    if currPatient in numCellsDict:
        currDictVal = numCellsDict[currPatient]
        updateVal = currDictVal + 1
        numCellsDict.update({currPatient:updateVal})

In [79]:
numCellsDict

{'TH067': 173,
 'TH103': 73,
 'TH107': 36,
 'TH146': 4,
 'TH150': 1,
 'TH155': 72,
 'TH156': 9,
 'TH157': 15,
 'TH158': 41,
 'TH169': 189,
 'TH171': 837,
 'TH172': 8,
 'TH174': 1,
 'TH179': 827,
 'TH179_Normal': 236,
 'TH183': 2,
 'TH185': 987,
 'TH199': 2,
 'TH205': 298,
 'TH208': 2,
 'TH210': 49,
 'TH217': 6,
 'TH218': 235,
 'TH220': 299,
 'TH222': 367,
 'TH223': 28,
 'TH225': 91,
 'TH226': 1109,
 'TH227': 81,
 'TH231': 537,
 'TH236': 621,
 'TH238': 632,
 'TH238_Normal': 292,
 'TH248': 608,
 'TH266': 636}

In [80]:
validationTable_patients['numCells'] = numCellsDict.values()
validationTable_patients

,patient,driver_gene,driver_mutation,mutations_found,numCells,numTumorCells,numTumorCells_w_coverage_to_ROI,numTumorCells_clinMut_found
0,TH248,EGFR,del19,"EGFR Q787Q,EGFR Q787Q,EGFR T903T,EGFR T903T,EG...",608,384,21,20
1,TH205,EGFR,L858R,"['ROS1 fusion', 'NTRK fusion', 'EGFR L858R', '...",298,9,1,0
2,TH217,EGFR,del19,[],6,4,0,0
3,TH185,EGFR,L858R,"['EGFR R521K', 'EGFR Q787Q', 'EGFR V536M', 'KR...",987,952,198,145
4,TH218,EGFR,L858R,"['EGFR P589L', 'BRAF G643G', 'EGFR T629T', 'EG...",235,11,0,0
5,TH172,BRAF,V600E,"['EGFR R521K', 'EGFR Q787Q', 'EGFR T629T']",8,0,0,0
6,TH226,EGFR,del19,"['ROS1 fusion', 'NTRK fusion', 'EGFR R1100S', ...",1109,205,10,10
7,TH174,WT,NaN,[],1,0,0,0
8,TH231,ALK,fusion,"['ROS1 fusion', 'EGFR R521K', 'EML4 fusion', '...",537,353,0,1
9,TH179_Normal,ALK,fusion,"['EGFR T903T', 'BRAF G643G', 'EGFR Q787Q']",236,11,0,0
10,TH171,ALK,fusion,"['ALK-EML4 fusion', 'BRAF G469R', 'EGFR V1142V...",837,720,0,3
11,TH227,ALK,intron 19 rearrangement,"['EGFR T629T', 'EGFR R521K', 'EGFR Q787Q', 'EG...",81,17,0,0
12,TH222,ROS1,fusion,"['EGFR L1034I', 'EGFR R1100S', 'BRAF G643G', '...",367,7,0,0
13,TH220,ALK,fusion,"['ALK-EML4 fusion', 'EGFR T629T', 'BRAF G643G'...",299,107,0,3
14,TH158,EGFR,del19,"['KRAS A11A', 'BRAF R682W', 'KRAS G12C']",41,3,0,0
15,TH223,EGFR,del19,"['EGFR T903T', 'BRAF G643G']",28,7,0,0
16,TH156,ALK,fusion,[],9,0,0,0
17,TH183,EGFR,del19,[],2,0,0,0
18,TH155,EGFR,del19,[],72,0,0,0
19,TH236,EGFR,del19,"['EGFR K754E', 'EGFR R1100S', 'EGFR P1019L', '...",621,101,19,18
20,TH146,ROS1,ROS1-CD74,['ROS1 fusion'],4,0,0,0
21,TH179,BRAF,V600E,"['BRAF G466E', 'EGFR Q787Q', 'KRAS C118S', 'KR...",827,137,4,0
22,TH157,ALK,fusion,[],15,0,0,0
23,TH169,EGFR,del19,"['EGFR T629T', 'EGFR R521K', 'KRAS A11A', 'ALK...",189,178,24,23
24,TH225,KRAS,G12C,"['EGFR T629T', 'EGFR R521K', 'EGFR Q787Q', 'EG...",91,20,17,0
25,TH103,ALK,fusion,"['ALK-EML4 fusion', 'ROS1 fusion', 'EGFR T629T...",73,65,0,4
26,TH238,BRAF,V600E,"['EGFR P589L', 'EGFR T629T', 'KRAS G13V', 'EGF...",632,260,2,0
27,TH067,EGFR,del19,"['ROS1 fusion', 'BRAF G643G', 'EML4 fusion', '...",173,97,0,0
28,TH199,KRAS,G12C,[],2,0,0,0
29,TH266,ALK,fusion,"['ALK-EML4 fusion', 'ROS1 fusion', 'KRAS K88K'...",636,1,0,0
30,TH150,WT,NaN,[],1,0,0,0
31,TH210,ALK,fusion,"['EGFR T903T', 'BRAF G643G']",49,15,0,0
32,TH208,EGFR,L861Q,"['EGFR T629T', 'EGFR R521K', 'EGFR L861Q', 'EG...",2,1,1,1
33,TH107,EGFR,del19,['KRAS G12C'],36,0,0,0
34,TH238_Normal,BRAF,V600E,"['NTRK fusion', 'EGFR T629T', 'EGFR R521K', 'E...",292,4,0,0

In [81]:
# why are there some duplicate vals in 'mutations_found'?
myStr = validationTable_patients['mutations_found'][0]
myLst = myStr.split(',')
mySet = set(myLst)
mySetList = list(mySet)
mySetList

['',
 'EGFR L858R',
 'EGFR S811F',
 'RET fusion',
 'EGFR del19',
 'KRAS G12A',
 'EGFR V843L',
 'ALK fusion',
 'EML4 fusion',
 'EGFR S921R',
 'KRAS A146P',
 'EGFR Q787Q',
 'EGFR G652G',
 'KRAS G12F',
 'KRAS G12C',
 'BRAF G643G',
 'EGFR T629T',
 'EGFR R1100S',
 'EGFR ins20',
 'BRAF G466E',
 'ROS1 fusion',
 'EGFR T903T']

In [82]:
validationTable_patients['mutations_found'][0] = list(mySet)
validationTable_patients

/Users/lincoln.harris/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,patient,driver_gene,driver_mutation,mutations_found,numCells,numTumorCells,numTumorCells_w_coverage_to_ROI,numTumorCells_clinMut_found
0,TH248,EGFR,del19,"[, EGFR L858R, EGFR S811F, RET fusion, EGFR de...",608,384,21,20
1,TH205,EGFR,L858R,"['ROS1 fusion', 'NTRK fusion', 'EGFR L858R', '...",298,9,1,0
2,TH217,EGFR,del19,[],6,4,0,0
3,TH185,EGFR,L858R,"['EGFR R521K', 'EGFR Q787Q', 'EGFR V536M', 'KR...",987,952,198,145
4,TH218,EGFR,L858R,"['EGFR P589L', 'BRAF G643G', 'EGFR T629T', 'EG...",235,11,0,0
5,TH172,BRAF,V600E,"['EGFR R521K', 'EGFR Q787Q', 'EGFR T629T']",8,0,0,0
6,TH226,EGFR,del19,"['ROS1 fusion', 'NTRK fusion', 'EGFR R1100S', ...",1109,205,10,10
7,TH174,WT,NaN,[],1,0,0,0
8,TH231,ALK,fusion,"['ROS1 fusion', 'EGFR R521K', 'EML4 fusion', '...",537,353,0,1
9,TH179_Normal,ALK,fusion,"['EGFR T903T', 'BRAF G643G', 'EGFR Q787Q']",236,11,0,0
10,TH171,ALK,fusion,"['ALK-EML4 fusion', 'BRAF G469R', 'EGFR V1142V...",837,720,0,3
11,TH227,ALK,intron 19 rearrangement,"['EGFR T629T', 'EGFR R521K', 'EGFR Q787Q', 'EG...",81,17,0,0
12,TH222,ROS1,fusion,"['EGFR L1034I', 'EGFR R1100S', 'BRAF G643G', '...",367,7,0,0
13,TH220,ALK,fusion,"['ALK-EML4 fusion', 'EGFR T629T', 'BRAF G643G'...",299,107,0,3
14,TH158,EGFR,del19,"['KRAS A11A', 'BRAF R682W', 'KRAS G12C']",41,3,0,0
15,TH223,EGFR,del19,"['EGFR T903T', 'BRAF G643G']",28,7,0,0
16,TH156,ALK,fusion,[],9,0,0,0
17,TH183,EGFR,del19,[],2,0,0,0
18,TH155,EGFR,del19,[],72,0,0,0
19,TH236,EGFR,del19,"['EGFR K754E', 'EGFR R1100S', 'EGFR P1019L', '...",621,101,19,18
20,TH146,ROS1,ROS1-CD74,['ROS1 fusion'],4,0,0,0
21,TH179,BRAF,V600E,"['BRAF G466E', 'EGFR Q787Q', 'KRAS C118S', 'KR...",827,137,4,0
22,TH157,ALK,fusion,[],15,0,0,0
23,TH169,EGFR,del19,"['EGFR T629T', 'EGFR R521K', 'KRAS A11A', 'ALK...",189,178,24,23
24,TH225,KRAS,G12C,"['EGFR T629T', 'EGFR R521K', 'EGFR Q787Q', 'EG...",91,20,17,0
25,TH103,ALK,fusion,"['ALK-EML4 fusion', 'ROS1 fusion', 'EGFR T629T...",73,65,0,4
26,TH238,BRAF,V600E,"['EGFR P589L', 'EGFR T629T', 'KRAS G13V', 'EGF...",632,260,2,0
27,TH067,EGFR,del19,"['ROS1 fusion', 'BRAF G643G', 'EML4 fusion', '...",173,97,0,0
28,TH199,KRAS,G12C,[],2,0,0,0
29,TH266,ALK,fusion,"['ALK-EML4 fusion', 'ROS1 fusion', 'KRAS K88K'...",636,1,0,0
30,TH150,WT,NaN,[],1,0,0,0
31,TH210,ALK,fusion,"['EGFR T903T', 'BRAF G643G']",49,15,0,0
32,TH208,EGFR,L861Q,"['EGFR T629T', 'EGFR R521K', 'EGFR L861Q', 'EG...",2,1,1,1
33,TH107,EGFR,del19,['KRAS G12C'],36,0,0,0
34,TH238_Normal,BRAF,V600E,"['NTRK fusion', 'EGFR T629T', 'EGFR R521K', 'E...",292,4,0,0

In [83]:
validationTable_patients['mutations_found'][0].remove('')

In [84]:
validationTable_patients['mutations_found'][0]

['EGFR L858R',
 'EGFR S811F',
 'RET fusion',
 'EGFR del19',
 'KRAS G12A',
 'EGFR V843L',
 'ALK fusion',
 'EML4 fusion',
 'EGFR S921R',
 'KRAS A146P',
 'EGFR Q787Q',
 'EGFR G652G',
 'KRAS G12F',
 'KRAS G12C',
 'BRAF G643G',
 'EGFR T629T',
 'EGFR R1100S',
 'EGFR ins20',
 'BRAF G466E',
 'ROS1 fusion',
 'EGFR T903T']

In [85]:
validationTable_patients['mutations_found'][1]

"['ROS1 fusion', 'NTRK fusion', 'EGFR L858R', 'EGFR T629T', 'EGFR V769L', 'EGFR R521K', 'RET fusion', 'EML4 fusion', 'EGFR Q787Q', 'ALK fusion', 'EGFR T903T', 'EGFR D1014N', 'KRAS G12C']"

In [86]:
validationTable_patients['mutations_found'][2]

'[]'

In [87]:
validationTable_patients['mutations_found'][3]

"['EGFR R521K', 'EGFR Q787Q', 'EGFR V536M', 'KRAS A146P', 'EGFR H1129Y', 'EGFR L1167V', 'EGFR S768I', 'EGFR G221V', 'EGFR L858R', 'EGFR V843L', 'BRAF S679N', 'EGFR A237V', 'BRAF G643G', 'EGFR G331R', 'EML4 fusion', 'EGFR F856L', 'BRAF V600E', 'ALK fusion', 'EGFR S921R', 'EGFR T903T', 'EGFR P589L', 'EGFR A237>?', 'EGFR T629T', 'EGFR I1093M', 'EGFR E709A', 'KRAS G13D', 'EGFR V769L']"

In [88]:
validationTable_patients.to_csv('validationTable_patients_w_cov.csv', index=False)

In [89]:
validationTable_cells.to_csv('validationTable_cells_w_cov.csv', index=False)